name: Court Checker
on:
  schedule:
    - cron: '0 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 * * *'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests pytz
      - run: python court_checker.py
